development:
  host: 127.0.0.1
  base: dc=gct,dc=local,dc=net
  bind_dn: cn=admin,dc=local,dc=net
  password: Pass001

test:
  host: 127.0.0.1
  base: dc=test,dc=local,dc=net
  bind_dn: cn=admin,dc=local,dc=net
  password: Pass001

production:
  host: 127.0.0.1
  method: :tls
  base: dc=gct,dc=local,dc=net
  bind_dn: cn=admin,dc=local,dc=net
  password: Pass001

